### ISSUE TITLE
Build fails: ln: csoundqt: Permission denied

### ISSUE THREAD

**Issue by yurivict** [CsoundQt/CsoundQt#277]
```
===>   Generating temporary packing list
gmake[1]: Entering directory '/wrkdirs/usr/ports/audio/csoundqt/work/CsoundQt-0.9.6'
cd /usr/local/bin; ln -sf CsoundQt-d-cs6 csoundqt
ln: csoundqt: Permission denied
gmake[1]: *** [Makefile:37867: install_target] Error 1
gmake[1]: Leaving directory '/wrkdirs/usr/ports/audio/csoundqt/work/CsoundQt-0.9.6'
```

It can only create links in directories under $(DESTDIR)$(PREFIX). Everything else is read-only.

Version 0.9.6
FreeBSD 12, built in the ports framework.

**Comment by tarmoj** [comment]
Hi,

Please explain more what are you intending to do and how do you run make install?
Are you building a pakcage or installing it for yourself?
In normal cases `sudo make install` should do.
You can also set the install directory something else with qmake options like:

qmake qcs.pro INSTALL_DIR=~ SHARE_DIR=~/.local/share

tarmo

**Comment by yurivict** [comment]
> Are you building a pakcage or installing it for yourself?

Nobody should be installing it for themselves manually, they should be installing from a package. Of course I am building a package.

-------

Here is the installation command that the framework runs:
```
===>   Generating temporary packing list
(cd /usr/ports/audio/csoundqt/work/CsoundQt-0.9.6 && /usr/bin/env QT_SELECT=qt5 QMAKEMODULES="/usr/ports/audio/csoundqt/work/CsoundQt-0.9.6/mkspecs/modules:/usr/local/lib/qt5/mkspecs/modules" XDG_DATA_HOME=/usr/ports/audio/csoundqt/work  XDG_CONFIG_HOME=/usr/ports/audio/csoundqt/work  HOME=/usr/ports/audio/csoundqt/work PATH=/usr/ports/audio/csoundqt/work/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin NO_PIE=yes MK_DEBUG_FILES=no MK_KERNEL_SYMBOLS=no SHELL=/bin/sh NO_LINT=YES PREFIX=/usr/local  LOCALBASE=/usr/local  CC="cc" CFLAGS="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing "  CPP="cpp" CPPFLAGS="-fno-omit-frame-pointer"  LDFLAGS=" -fstack-protector-strong " LIBS=""  CXX="c++" CXXFLAGS="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  "  MANPREFIX="/usr/local" BSD_INSTALL_PROGRAM="install  -s -m 555"  BSD_INSTALL_LIB="install  -s -m 0644"  BSD_INSTALL_SCRIPT="install  -m 555"  BSD_INSTALL_DATA="install  -m 0644"  BSD_INSTALL_MAN="install  -m 444"  gmake -f Makefile INSTALL_ROOT=/usr/ports/audio/csoundqt/work/stage install )
gmake[2]: Entering directory '/usr/ports/audio/csoundqt/work/CsoundQt-0.9.6'
cd /usr/local/bin; ln -sf CsoundQt-d-cs6 csoundqt
ln: csoundqt: Permission denied
gmake[2]: *** [Makefile:38471: install_target] Error 1
gmake[2]: Leaving directory '/usr/ports/audio/csoundqt/work/CsoundQt-0.9.6'
*** Error code 2
```

**Comment by tarmoj** [comment]
Hi,

Probably you need to do some local tweaking (some changes with sed)
The problem comes from qcs.pro: 202
target.commands = cd $$INSTALL_DIR/bin; ln -sf $$TARGET csoundqt
I was asked to do it this way to enable building pacakge on Arch Linux (to have the link relative).
Now I see that the link has to be relative but it must be copied to to the install dir.

It should be something like i will fix it a bit later.
target.commands = cd $$OUT_PWD/$$DESTDIR/; ln -sf $$TARGET csoundqt; cp csoundqt $$target.path
I will test and try it later. If you get it fixed before, thank you.
tarmo

**Comment by yurivict** [comment]
All directories should be relative to ```$(DESTDIR)``` - the staging directory.

**Comment by tarmoj** [comment]
Feel free to change it as you need and please report back if you find a
good solution. I will have a look later.

Tarmo

L, 13. juuli 2019 12:18 yuri@FreeBSD <notifications@github.com> kirjutas:

**Comment by yurivict** [comment]
Sorry, I don't have resources to fix problems in packaged software, I can only change ports.
I am a port maintainer, and not a user of csound. So I will wait until this is resolved upstream.
I am pretty sure that Debian packages and rpm package would all fail for the same reason.
Arch is just a very insecure system, their builds aren't following proper secure build procedures. They are probably building everything as root and don't even notice such problems.

**Comment by tarmoj** [comment]
Hi,

I changed now the target section to:

    target.path = $$INSTALL_DIR/bin
    target.commands = cd $$OUT_PWD/$$DESTDIR/; ln -sf $$TARGET csoundqt #  ln -sf $$target.path/$$TARGET $$target.path/csoundqt #	 create link always with the same name, keep the original binary with its unique name
    #target.files = $$OUT_PWD/$$DESTDIR/$$TARGET # do not install with the full name
    target.files += $$OUT_PWD/$$DESTDIR/csoundqt # but as csoundqt

Now it creates an relative link csoundqt to the build program with full name (like CsoundQt-d-pt-html) in the build directory and installs only csoundqt to the install dir.  All the unix rules are a bit messy as they are rewrite of several times but should do, I hope.

I have never done and don't know about packaging, please have a look to the arch linux and debian rules, hopefully they give an idea:

https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/csoundqt

https://sources.debian.org/src/csoundqt/0.9.4-1/debian/rules/
https://sources.debian.org/src/csoundqt/0.9.4-1/debian/patches/
https://sources.debian.org/src/csoundqt/0.9.4-1/debian/ 

Greetings,
tar,p

**Comment by tarmoj** [comment]
By the way, I pushed the change to develop branch. Do you pull from there or from master?

Tarmo

**Comment by yurivict** [comment]
I tried the latest master ```0.9.6-1-g20c16da3``` and it fails with a different message:
```
===>   Generating temporary packing list
gmake[2]: Entering directory '/usr/ports/audio/csoundqt/work/CsoundQt-0.9.6-1-g20c16da3'
cd /usr/ports/audio/csoundqt/work/CsoundQt-0.9.6-1-g20c16da3/bin/; ln -sf CsoundQt-d-cs6 csoundqt
rm -f /usr/local/share/applications/CsoundQt.desktop && desktop-file-install --mode=644 --dir=/usr/local/share/applications /usr/ports/audio/csoundqt/work/CsoundQt-0.9.6-1-g20c16da3/csoundqt.desktop
Error on file "/usr/ports/audio/csoundqt/work/CsoundQt-0.9.6-1-g20c16da3/csoundqt.desktop": Failed to create file ?/usr/local/share/applications/csoundqt.desktop.19IT4Z?: Permission denied
gmake[2]: *** [Makefile:38476: install_desktop] Error 1
gmake[2]: Leaving directory '/usr/ports/audio/csoundqt/work/CsoundQt-0.9.6-1-g20c16da3'
```

**Comment by tarmoj** [comment]
Please send me more information how you build, how and with which parameters you run qmake, perhaps a link to your build script? This is on FreeBSD, right?  I have no previous experience. Has CsodunQt be built/packages on FreeBSD before?


tarmo

**Comment by yurivict** [comment]
Confugure command:
```
cd /usr/ports/audio/csoundqt/work/CsoundQt-0.9.6-1-g20c16da3 &&  /usr/bin/env MAKE=gmake QT_SELECT=qt5 QMAKEMODULES="/usr/ports/audio/csoundqt/work/CsoundQt-0.9.6-1-g20c16da3/mkspecs/modules:/usr/local/lib/qt5/mkspecs/modules" QTDIR="/usr/local/lib/qt5" QMAKE="/usr/local/lib/qt5/bin/qmake"  MOC="/usr/local/lib/qt5/bin/moc" RCC="/usr/local/lib/qt5/bin/rcc" UIC="/usr/local/lib/qt5/bin/uic"  QMAKESPEC="/usr/local/lib/qt5/mkspecs/freebsd-$(ccver="$(c++ --version)"; case "$ccver" in *clang*) echo clang ;; *) echo g++ ;; esac)" XDG_DATA_HOME=/usr/ports/audio/csoundqt/work  XDG_CONFIG_HOME=/usr/ports/audio/csoundqt/work  HOME=/usr/ports/audio/csoundqt/work PATH=/usr/ports/audio/csoundqt/work/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin SHELL=/bin/sh CONFIG_SHELL=/bin/sh /usr/local/lib/qt5/bin/qmake CONFIG+="CSOUND_API_INCLUDE_DIR=/usr/local/include/csound CSOUND_LIBRARY_DIR=/usr/local/lib build64"  INSTALL_DIR=/usr/local SHARE_DIR=/usr/local/share  qcs.pro -spec /usr/local/lib/qt5/mkspecs/freebsd-$(ccver="$(c++ --version)"; case "$ccver" in *clang*) echo clang ;; *) echo g++ ;; esac)  QMAKE_CC="cc" QMAKE_CXX="c++"  QMAKE_LINK_C="cc" QMAKE_LINK_C_SHLIB="cc"  QMAKE_LINK="c++" QMAKE_LINK_SHLIB="c++"  QMAKE_CFLAGS="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing "  QMAKE_CXXFLAGS="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  "  QMAKE_LFLAGS=" -fstack-protector-strong "  QMAKE_LIBS=""  QMAKE_CFLAGS_DEBUG=""  QMAKE_CFLAGS_RELEASE=""  QMAKE_CXXFLAGS_DEBUG=""  QMAKE_CXXFLAGS_RELEASE=""  PREFIX="/usr/local" CONFIG+="release"  CONFIG-="debug separate_debug_info" -recursive     
```


Build command:
```
(cd /usr/ports/audio/csoundqt/work/CsoundQt-0.9.6-1-g20c16da3; if ! /usr/bin/env QT_SELECT=qt5 QMAKEMODULES="/usr/ports/audio/csoundqt/work/CsoundQt-0.9.6-1-g20c16da3/mkspecs/modules:/usr/local/lib/qt5/mkspecs/modules" XDG_DATA_HOME=/usr/ports/audio/csoundqt/work  XDG_CONFIG_HOME=/usr/ports/audio/csoundqt/work  HOME=/usr/ports/audio/csoundqt/work PATH=/usr/ports/audio/csoundqt/work/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin NO_PIE=yes MK_DEBUG_FILES=no MK_KERNEL_SYMBOLS=no SHELL=/bin/sh NO_LINT=YES PREFIX=/usr/local  LOCALBASE=/usr/local  CC="cc" CFLAGS="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing "  CPP="cpp" CPPFLAGS="-fno-omit-frame-pointer"  LDFLAGS=" -fstack-protector-strong " LIBS=""  CXX="c++" CXXFLAGS="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  "  MANPREFIX="/usr/local" BSD_INSTALL_PROGRAM="install  -s -m 555"  BSD_INSTALL_LIB="install  -s -m 0644"  BSD_INSTALL_SCRIPT="install  -m 555"  BSD_INSTALL_DATA="install  -m 0644"  BSD_INSTALL_MAN="install  -m 444" gmake -f Makefile -j8  all; then  if [ -n "Try to set MAKE_JOBS_UNSAFE=yes and rebuild before reporting the failure to the maintainer." ] ; then  echo "===> Compilation failed unexpectedly.";  (echo "Try to set MAKE_JOBS_UNSAFE=yes and rebuild before reporting the failure to the maintainer.") | /usr/bin/fmt 75 79 ;  fi;  false;  fi)
```


Install command:
```
(cd /usr/ports/audio/csoundqt/work/CsoundQt-0.9.6-1-g20c16da3 && /usr/bin/env QT_SELECT=qt5 QMAKEMODULES="/usr/ports/audio/csoundqt/work/CsoundQt-0.9.6-1-g20c16da3/mkspecs/modules:/usr/local/lib/qt5/mkspecs/modules" XDG_DATA_HOME=/usr/ports/audio/csoundqt/work  XDG_CONFIG_HOME=/usr/ports/audio/csoundqt/work  HOME=/usr/ports/audio/csoundqt/work PATH=/usr/ports/audio/csoundqt/work/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin NO_PIE=yes MK_DEBUG_FILES=no MK_KERNEL_SYMBOLS=no SHELL=/bin/sh NO_LINT=YES PREFIX=/usr/local  LOCALBASE=/usr/local  CC="cc" CFLAGS="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing "  CPP="cpp" CPPFLAGS="-fno-omit-frame-pointer"  LDFLAGS=" -fstack-protector-strong " LIBS=""  CXX="c++" CXXFLAGS="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  "  MANPREFIX="/usr/local" BSD_INSTALL_PROGRAM="install  -s -m 555"  BSD_INSTALL_LIB="install  -s -m 0644"  BSD_INSTALL_SCRIPT="install  -m 555"  BSD_INSTALL_DATA="install  -m 0644"  BSD_INSTALL_MAN="install  -m 444"  gmake -f Makefile INSTALL_ROOT=/usr/ports/audio/csoundqt/work/stage install )
```

**Comment by yurivict** [comment]
It still fails to build:
```
===>   Generating temporary packing list
gmake[1]: Entering directory '/wrkdirs/usr/ports/audio/csoundqt/work/CsoundQt-0.9.6-30-g5447686c'
cd /wrkdirs/usr/ports/audio/csoundqt/work/CsoundQt-0.9.6-30-g5447686c/bin/; ln -sf CsoundQt-d-cs6 csoundqt
rm -f /usr/local/share/applications/CsoundQt.desktop && desktop-file-install --mode=644 --dir=/usr/local/share/applications /wrkdirs/usr/ports/audio/csoundqt/work/CsoundQt-0.9.6-30-g5447686c/csoundqt.desktop
Error on file "/wrkdirs/usr/ports/audio/csoundqt/work/CsoundQt-0.9.6-30-g5447686c/csoundqt.desktop": Failed to create file ?/usr/local/share/applications/csoundqt.desktop.IE7CE0?: Permission denied
gmake[1]: *** [Makefile:37987: install_desktop] Error 1
gmake[1]: Leaving directory '/wrkdirs/usr/ports/audio/csoundqt/work/CsoundQt-0.9.6-30-g5447686c'
```

Te mistake is here: https://github.com/CsoundQt/CsoundQt/blob/develop/qcs.pro#L210 You shouldn't delete files in read-only locations. Installation should be done into $(DESTDIR)$(PREFIX)/...

**Comment by tarmoj** [comment]
Hi,

seems that  we are having still hard time understanding each other:


how can you install anything to a folder where you have no write
permissions?
Is it so that you will install to a temporary stage directory and then make
the package from there?

If you want to install to:

$(DESTDIR)$(PREFIX)

and I assume you must have write permissions to $DESTDIR

Then you should set qmake parameters
qmake qcs.pro INSTALL_DIR=$(DESTDIR)$(PREFIX)
SHARE_DIR=$(DESTDIR)/$(PREFIX)/share

is it in your case perhaps something like:
qmake qcs.pro INSTALL_DIR=
/wrkdirs/usr/ports/audio/csoundqt/work/CsoundQt-0.9.6-30-g5447686c/build
SHARE_DIR=/wrkdirs/usr/ports/audio/csoundqt/work/CsoundQt-0.9.6-30-g5447686c
/build/

For example I tried with command:
qmake-qt5 qcs.pro INSTALL_DIR=./tmpbuild SHARE_DIR=./tmpbuild/share

and it worked as expected.

Also packagers on Debian and Fedora are fine with it, I don't know.

I fixed now another bug ib  qcs.pro but that was not related to your
problem. Anyway, please pull again and give a try with proper INSTALL_DIR
and SHARE_DIR.


Hope it helps.

tarmo






Do you want to say that


Kontakt yuri@FreeBSD (<notifications@github.com>) kirjutas kuupäeval P, 12.
jaanuar 2020 kell 10:17:

**Comment by yurivict** [comment]
> Is it so that you will install to a temporary stage directory and then make
the package from there?

Yes, this is how all packages are created.



This is a regression between 0.9.5 and 0.9.6-30 (and earlier sub-revisions).
0.9.5 didn't have such problem. Normally, it just picks DESTDIR by itself.

About the .desktop: these 2 lines are wrong:
https://github.com/CsoundQt/CsoundQt/blob/develop/qcs.pro#L217
https://github.com/CsoundQt/CsoundQt/blob/develop/qcs.pro#L218

No need to delete the file, and it is not installed with any special command like desktop-file-install. It is a regular file and can be installed by just copying it.

Please see how qBittorrent handles the .desktop file from qmake: https://github.com/qbittorrent/qBittorrent/blob/master/unixconf.pri#L38

Then, when I remove the above 2 lines this fails:
> /bin/sh: linuxdeploy: not found

I don't know what is ```linuxdeploy```, it shouldn't be needed and I am on FreeBSD anyway.

----------------

You should keep in mind that the purpose of the installation procedure is to play nicely with package builders, because users don't build their software, they install packages. Installation is done into $(DESTDIR) that is a temporary stage directory, and then into $(PREFIX) which is where these files will eventually land.

**Comment by yurivict** [comment]
I recommend that you switch to cmake. qmake is terrible for large projects, it doesn't scale.

Your .pro files are 2157 lines in total (!!!!). This should be a red flag that something is going in a very wrong direction. They should be 200-300 lines long.

I also develop the Qt5-based project, and its cmake file is very short: https://github.com/yurivict/nn-insight/blob/master/CMakeLists.txt

I would say that cmake is absolutely excellent in handling Qt projects.

**Comment by tarmoj** [comment]
Hi,

Thanks, that it built with 0.9.5 is good starting point. I made the
changes  according to suggestions from other packagers and examples. Sorry
that it broke the build fro FreeBSD and I never understood from mails that
it used to work before.

I changed  the desktop installing rule back to:
desktop.path=$$SHARE_DIR/applications
desktop.files = $$PWD/csoundqt.desktop

I hope it works now...

I am a little bit afraid that also this recent change does not work in your
build system as it needs to create the link in the install dir. Please let
me know:
postinstall.path = $$INSTALL_DIR/bin
postinstall.commands = cd $$INSTALL_DIR/bin; ln -sf $$TARGET csoundqt


Sorry for the linuxdeploy rule -  it should be commented out as I am
experimenting with creating an AppImage and pushed up a version where the
comment mark was not in place. Now fixed.

Tip about cmake is in place. I took the software maintenance over from
previous author and I agree the configuration files is quite a thick
forest. Nevertheless I cannot contribute much time to rewrite all of it but
will keep in mind with future projects.

Thanks for your patience, I hope we will get it sorted out soon!

tarmo


Kontakt yuri@FreeBSD (<notifications@github.com>) kirjutas kuupäeval P, 12.
jaanuar 2020 kell 20:11:

**Comment by yurivict** [comment]
> I took the software maintenance over from previous author and I agree the configuration files is quite a thick forest.

I totally understand!


------------------

Now it breaks in this way:
```
===>   Generating temporary packing list
gmake[2]: Entering directory '/usr/ports/audio/csoundqt/work/CsoundQt-0.9.7-rc1-2-g86e0c4cd'
/usr/local/lib/qt5/bin/qmake -install qinstall -exe /usr/ports/audio/csoundqt/work/CsoundQt-0.9.7-rc1-2-g86e0c4cd/bin/CsoundQt-d-cs6 /usr/ports/audio/csoundqt/work/stage/usr/local/bin/CsoundQt-d-cs6
cd /usr/local/bin; ln -sf CsoundQt-d-cs6 csoundqt
ln: csoundqt: Permission denied
```

**Comment by tarmoj** [comment]
Ok, this is what I was afraid of.
I think I can fix it tomorrow.
Tarmo


P, 12. jaanuar 2020 22:53 yuri@FreeBSD <notifications@github.com> kirjutas:

**Comment by tarmoj** [comment]
Hi,

Still I need to ask one thing before I make any change -  you said that in
v0.9.5 the build worked. Here is the desktop part:

target.path = $$INSTALL_DIR/bin
target.commands = ln -sf $$TARGET $(INSTALL_ROOT)/$$INSTALL_DIR/bin/csoundqt
# create link always with the same name
 target.files = $$OUT_PWD/$$DESTDIR/$$TARGET

I would assume that  ln -sf $$TARGET $(INSTALL_ROOT)/$$INSTALL_DIR/bin/csoundqt
should fail as other similar commands. Here there is $(INSTALL_ROOT) prefix
that got lost at some point...
I wonder if this makes the change? And then

postinstall.commands = cd $(INSTALL_ROOT)/$$INSTALL_DIR/bin; ln -sf
$$TARGET csoundqt

- would this work?

The link should be relative, not with the whole path since it created
problems on Arch Linux this way.

The other only solution that I see for FreeBSD is to install only the full
name binary ($$TARGET) that looks something like  CsoundQt-d-html-cs6 and
change with sed the desktop file so that it points to correct executable
(now it is 'csoundqt' ).
OR: maybe most sensible: to add some option to qmake that configure the
FreeBSD build this way as it used to be

I  don't want to change the naming convention (so that the target wouldbe
just csoundqt), as it is now,  it is possible to see from the executables
name, what it is capable for and for convenience, it is good to have
csoudqt, too. So I would like to keep it at least for the other systems.
That's why the link is important.

Thanks!
tarmo


tarmo



Kontakt Tarmo Johannes (<trmjhnns@gmail.com>) kirjutas kuupäeval P, 12.
jaanuar 2020 kell 23:21:

**Comment by yurivict** [comment]
> postinstall.commands = cd $(INSTALL_ROOT)/$$INSTALL_DIR/bin; ln -sf
$$TARGET csoundqt
> - would this work?



This should work, I think.

**Comment by tarmoj** [comment]
Hi,

I think I finally understood the issue -  I learned that  $(INSTALL_ROOT)
is used for build systems like you  are using where. Since qmake places it
automatically in caseof  normal install instructions and in usual case it
is empty anyway (when software will be installed to /usr/... )  I never
payed attention to it to add it to install commands like rm, ln, cp or
similar.

I really hope I got qcs.pro correct now, please try.

tarmo

Kontakt yuri@FreeBSD (<notifications@github.com>) kirjutas kuupäeval E, 13.
jaanuar 2020 kell 21:25:

**Comment by yurivict** [comment]
```
===>   Generating temporary packing list
gmake[2]: Entering directory '/usr/ports/audio/csoundqt/work/CsoundQt-0.9.7-rc1-3-g83fa57b6'
/usr/local/lib/qt5/bin/qmake -install qinstall -exe /usr/ports/audio/csoundqt/work/CsoundQt-0.9.7-rc1-3-g83fa57b6/bin/CsoundQt-d-cs6 /usr/ports/audio/csoundqt/work/stage/usr/local/bin/CsoundQt-d-cs6
cd /usr/ports/audio/csoundqt/work/stage//usr/local/bin; ln -sf CsoundQt-d-cs6 csoundqt
/usr/local/lib/qt5/bin/qmake -install qinstall /usr/ports/audio/csoundqt/work/CsoundQt-0.9.7-rc1-3-g83fa57b6/csoundqt.desktop /usr/ports/audio/csoundqt/work/stage/usr/local/share/applications/csoundqt.desktop
/usr/local/lib/qt5/bin/qmake -install qinstall /usr/ports/audio/csoundqt/work/CsoundQt-0.9.7-rc1-3-g83fa57b6/images/csoundqt.svg /usr/ports/audio/csoundqt/work/stage/usr/local/share/icons/hicolor/scalable/apps/csoundqt.svg
cd /usr/ports/audio/csoundqt/work/CsoundQt-0.9.7-rc1-3-g83fa57b6/mime-types/; ./add_csound_mimetypes.sh /usr/local/share
cp: /usr/local/share/icons/hicolor/128x128/mimetypes/csound.png: Permission denied
cp: /usr/local/share/mime/packages/x-csound-csd.xml: Permission denied
cp: /usr/local/share/mime/packages/x-csound-inc.xml: Permission denied
cp: /usr/local/share/mime/packages/x-csound-orc.xml: Permission denied
cp: /usr/local/share/mime/packages/x-csound-sco.xml: Permission denied
cp: /usr/local/share/mime/packages/x-csound-udo.xml: Permission denied
Updating MIME database in /usr/local/share/mime...

Parsing source file /usr/local/share/mime/packages/akonadi-mime.xml...
Parsing source file /usr/local/share/mime/packages/brasero.xml...
Parsing source file /usr/local/share/mime/packages/djvulibre-mime.xml...
Parsing source file /usr/local/share/mime/packages/freedesktop.org.xml...
Parsing source file /usr/local/share/mime/packages/gcr-crypto-types.xml...
Parsing source file /usr/local/share/mime/packages/kde5.xml...
Parsing source file /usr/local/share/mime/packages/org.gnome.meld.xml...
Parsing source file /usr/local/share/mime/packages/x-gtkwave-extension-ae2.xml...
Parsing source file /usr/local/share/mime/packages/x-gtkwave-extension-aet.xml...
Parsing source file /usr/local/share/mime/packages/x-gtkwave-extension-evcd.xml...
Parsing source file /usr/local/share/mime/packages/x-gtkwave-extension-fst.xml...
Parsing source file /usr/local/share/mime/packages/x-gtkwave-extension-ghw.xml...
Parsing source file /usr/local/share/mime/packages/x-gtkwave-extension-gtkw.xml...
Parsing source file /usr/local/share/mime/packages/x-gtkwave-extension-lx2.xml...
Parsing source file /usr/local/share/mime/packages/x-gtkwave-extension-lxt.xml...
Parsing source file /usr/local/share/mime/packages/x-gtkwave-extension-lxt2.xml...
Parsing source file /usr/local/share/mime/packages/x-gtkwave-extension-vcd.xml...
Parsing source file /usr/local/share/mime/packages/x-gtkwave-extension-vzt.xml...
I/O error : Permission denied
I/O error : Permission denied
Failed to write XML file; For permission problems, try rerunning as root
You may need to log out and log in to make changes effective.
rm -rf /usr/ports/audio/csoundqt/work/stage//usr/local/share/qutecsound
/usr/local/lib/qt5/bin/qmake -install qinstall /usr/ports/audio/csoundqt/work/CsoundQt-0.9.7-rc1-3-g83fa57b6/src/Examples /usr/ports/audio/csoundqt/work/stage/usr/local/share/csoundqt/Examples
/usr/local/lib/qt5/bin/qmake -install qinstall /usr/ports/audio/csoundqt/work/CsoundQt-0.9.7-rc1-3-g83fa57b6/templates /usr/ports/audio/csoundqt/work/stage/usr/local/share/csoundqt/templates
gmake[2]: Leaving directory '/usr/ports/audio/csoundqt/work/CsoundQt-0.9.7-rc1-3-g83fa57b6'
mv: rename /usr/ports/audio/csoundqt/work/stage/usr/local/share/CsoundQt/Examples to /usr/ports/audio/csoundqt/work/stage/usr/local/share/examples/CsoundQt: No such file or directory
*** Error code 1
```

**Comment by tarmoj** [comment]
Oh, that was another $(INSTALL_ROOT) missing. Fixed and pushed up.

tarmo

Kontakt yuri@FreeBSD (<notifications@github.com>) kirjutas kuupäeval E, 13.
jaanuar 2020 kell 23:29:

**Comment by yurivict** [comment]
Now it fails lie this:
```
mv: rename /usr/ports/audio/csoundqt/work/stage/usr/local/share/CsoundQt/Examples to /usr/ports/audio/csoundqt/work/stage/usr/local/share/examples/CsoundQt: No such file or directory
```

**Comment by yurivict** [comment]
Ah, never mind, this was the port's script that failed.

Thank you for your help, Tarmo!

**Comment by tarmoj** [comment]
Thanks a lot for you patience, tips and making the FreeBSD port!!

By the way, I made an experimental AppImage build (that is supposed to work on any Linux kind of operating system, all dependencies installed). If you have time, can you try if it starts on your system (download, make executable and start):
https://github.com/CsoundQt/CsoundQt/releases/download/0.9.7-rc1/CsoundQt-x86_64-Linux.AppImage

tarmo

**Comment by yurivict** [comment]
I tried the AppImage in the Ubuntu VM, and the application started fine.

Cheers,
Yuri
